AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SetbackPolylineFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://solarlab-sam-lambda/47280777ed4ee9eb1d309f386249e604
      Handler: setbackPolylineCalculationAPP.lambdaHandler
      Runtime: nodejs10.x
      Timeout: 15
  SetbackPolylinePitchedRoofFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://solarlab-sam-lambda/47280777ed4ee9eb1d309f386249e604
      Handler: setbackPolylinePitchedRoofCalculationAPP.lambdaHandler
      Runtime: nodejs10.x
      Timeout: 15
  PassagePolylineFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://solarlab-sam-lambda/47280777ed4ee9eb1d309f386249e604
      Handler: passageSetbackCalculationAPP.lambdaHandler
      Runtime: nodejs10.x
      Timeout: 15
  FlatRoofPVCalculationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://solarlab-sam-lambda/47280777ed4ee9eb1d309f386249e604
      Handler: flatRoofPVCalculationAPP.lambdaHandler
      Runtime: nodejs10.x
      Timeout: 15
  createPanelFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://solarlab-sam-lambda/47280777ed4ee9eb1d309f386249e604
      Handler: createPanelAPP.lambdaHandler
      Runtime: nodejs10.x
      Timeout: 15
  getPanelFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://solarlab-sam-lambda/47280777ed4ee9eb1d309f386249e604
      Handler: getPanelAPP.lambdaHandler
      Runtime: nodejs10.x
      Timeout: 15
  createInverterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://solarlab-sam-lambda/47280777ed4ee9eb1d309f386249e604
      Handler: createInverterAPP.lambdaHandler
      Runtime: nodejs10.x
      Timeout: 15
