Transform: AWS::Serverless-2016-10-31
Resources:
  SetbackCoordinateFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs10.x
      CodeUri: ./
      Handler: index.lambdaHandler
      Timeout: 15
